name: MAJ Bandes Annonces Automatique

on:
  schedule:
    - cron: '15 7 * * *'  # UTC -> 09h15 France (UTC+2)
  workflow_dispatch:      # Permet aussi de lancer manuellement via GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Cloner le dépôt
        uses: actions/checkout@v3

      - name: 🐍 Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install

      - name: ▶️ Lancer le script
        run: |
          python maj_bandes_annonces.py

      - name: 🔁 Commit des fichiers modifiés (si besoin)
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "MAJ auto des bandes-annonces" || echo "Aucun changement"
          git push
