name: Exécution automatique du scraper de bandes-annonces

on:
  schedule:
    - cron: '0 8,18 * * *'  # Tous les jours à 10h et 20h heure française (UTC+2)
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  run_scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configuration de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Installation des dépendances Python
        run: |
          python -m pip install --upgrade pip
          pip install playwright beautifulsoup4
          playwright install chromium

      - name: Exécution du script de scraping
        run: python scraper_bandes_annonces.py

      - name: Commit automatique des fichiers mis à jour
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🎬 Mise à jour automatique des bandes-annonces"
          files: |
            bande_annonces_blocs.html
            bande_annonces_maj.html
            scripts/bande_annonces_log.json
          commit_author: "GitHub Actions <actions@github.com>"
          commit_user_email: "actions@github.com"
